GET http://localhost:8000/api/products

###
GET http://localhost:8000/api/products?limit=2&category=1/7

###
GET http://localhost:8000/api/products
    ?limit=1

###
POST http://localhost:8000/api/product
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8000/api/product
Content-Type: application/x-www-form-urlencoded



###
GET http://localhost:8000/api/product/6107af929e9d7f3a14e44541

###
POST http://localhost:8000/user/register
Content-Type: application/x-www-form-urlencoded

email=example@gmail.com
&password=123456789
&fullname=Nguyen Thanh Huy
&sex=male
&phone=0907579269

###
POST http://localhost:8000/auth/login
Content-Type: application/x-www-form-urlencoded

email=example@gmail.com
&password=123456789

###
GET http://localhost:8000/api/products?pricemax=10000&limit=3&

###
PUT http://localhost:8000/api/product/6107b0899e9d7f3a14e44553/rating
Content-Type: application/x-www-form-urlencoded

rating=5